apiVersion: networking.k8s.io/v1
kind: Ingress # Tipo de recurso: Ingress
metadata: # Metadatos del Ingress
  name: delieats-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec: # Especificación del Ingress
  ingressClassName: nginx
  rules: # Reglas de enrutamiento para el Ingress
    - host: www.delieats.com # Dominio para acceder a la aplicación
      http:
        paths: # Rutas para enrutar el tráfico
          - path: /
            pathType: Prefix
            backend:
              service: # Servicio al que se enruta el tráfico
                name: delieats-front
                port:
                  number: 80
