apiVersion: v1
kind: Service # Tipo de recurso: Service
metadata: # Metadatos del servicio
  name: delieats-front
spec: # Especificación del servicio
  type: ClusterIP # Tipo de servicio: ClusterIP para comunicación interna
  selector: # Selector para identificar los pods del frontend
    app: delieats
    component: frontend
  ports: # Puertos expuestos por el servicio
  - port: 80
    targetPort: 80