# ==========================================
# PVC para las fotos/uploads del backend
# ==========================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fotos-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ==========================================
# PVC para los datos de MySQL
# ==========================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi