spring.application.name=orders-service
jwt.secret=mi_clave_secreta_super_segura_y_muy_larga_1234567890
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CorsFilter=DEBUG
server.servlet.context-path=/api

# ==============================================================
# CONFIGURACIÓN DE BASE DE DATOS MYSQL (ACTIVA)
# ==============================================================
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/orders_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuración de Hibernate para crear tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Deshabilitar la consola de H2 si ya no se usa
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
